In [1]:
import numpy as np

In [6]:
arr1 = np.zeros(10, int)
arr1[4] = 1
arr1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [7]:
arr2 = np.arange(10, 50)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
arr3 = np.arange(9).reshape((3, 3))
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr4 = np.array([1, 2, 0, 0, 4, 0])
np.argwhere(arr4)

array([[0],
       [1],
       [4]], dtype=int64)

In [19]:
arr5 = np.random.random((10, 10))
arr5.min(), arr5.max()

(0.013799233745571127, 0.9808242592418799)

In [31]:
arr6 = np.random.random(30)
arr6.mean()

0.4783051762497513